

export const MOCKED_LINKS = [
  {
    name: 'GitHub',
    image: '/images/Octocat.png',
    url: 'rob.io/github',
    tags: ['GitHub', 'Robotics', 'Object-Oriented programming'],
    size: 'BIG',
  },
  {
    name: 'Intro a ROS',
    image: '/images/ROS.png',
    url: 'rob.io/2XpfDeG',
    tags: ['GitHub', 'ROS', 'Youtube'],
    size: 'BIG',
  },
  {
    name: 'RoboCupido',
    image: '/images/RoboCupido.png',
    url: 'rob.io/robocupido',
    tags: ['GitHub', 'ML', 'RoBorregos'],
    size: 'BIG',
  },
  {
    name: 'Intro a ROS',
    image: '/images/ROS.png',
    url: 'rob.io/2XpfDeG',
    tags: ['GitHub', 'ROS', 'Youtube'],
    size: 'BIG',
  },
  {
    name: 'GitHub',
    image: '/images/Octocat.png',
    url: 'rob.io/github',
    tags: ['GitHub', 'Robotics', 'Object-Oriented programming'],
    size: 'MEDIUM',
  },
  {
    name: 'Intro a ROS',
    image: '/images/ROS.png',
    url: 'rob.io/2XpfDeG',
    tags: ['GitHub', 'ROS', 'Youtube'],
    size: 'MEDIUM',
  },
  {
    name: 'RoboCupido',
    image: '/images/RoboCupido.png',
    url: 'rob.io/robocupido',
    tags: ['GitHub', 'ML', 'RoBorregos'],
    size: 'MEDIUM',
  },
  {
    name: 'GitHub',
    image: '/images/Octocat.png',
    url: 'rob.io/github',
    tags: ['GitHub', 'Robotics', 'Object-Oriented programming'],
    size: 'MEDIUM',
  },
  {
    name: 'RoboCupido',
    image: '/images/RoboCupido.png',
    url: 'rob.io/robocupido',
    tags: ['GitHub', 'ML', 'RoBorregos'],
    size: 'MEDIUM',
  },
  {
    name: 'Intro a ROS',
    image: '/images/ROS.png',
    url: 'rob.io/2XpfDeG',
    tags: ['GitHub', 'ROS', 'Youtube'],
    size: 'SMALL',
  },
  {
    name: 'RoboCupido',
    image: '/images/RoboCupido.png',
    url: 'rob.io/robocupido',
    tags: ['GitHub', 'ML', 'RoBorregos'],
    size: 'SMALL',
  },
  {
    name: 'Intro a ROS',
    image: '/images/ROS.png',
    url: 'rob.io/2XpfDeG',
    tags: ['GitHub', 'ROS', 'Youtube'],
    size: 'SMALL',
  },
  {
    name: 'RoboCupido',
    image: '/images/RoboCupido.png',
    url: 'rob.io/robocupido',
    tags: ['GitHub', 'ML', 'RoBorregos'],
    size: 'SMALL',
  },
  {
    name: 'GitHub',
    image: '/images/Octocat.png',
    url: 'rob.io/github',
    tags: ['GitHub', 'Robotics', 'Object-Oriented programming'],
    size: 'SMALL',
  },
  {
    name: 'Intro a ROS',
    image: '/images/ROS.png',
    url: 'rob.io/2XpfDeG',
    tags: ['GitHub', 'ROS', 'Youtube'],
    size: 'SMALL',
  },
  {
    name: 'RoboCupido',
    image: '/images/RoboCupido.png',
    url: 'rob.io/robocupido',
    tags: ['GitHub', 'ML', 'RoBorregos'],
    size: 'SMALL',
  },
  {
    name: 'RoboCupido',
    image: '/images/RoboCupido.png',
    url: 'rob.io/robocupido',
    tags: ['GitHub', 'ML', 'RoBorregos'],
    size: 'SMALL',
  },
];